### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lootmann** [Lootmann/Problems.v2#3]
# Todo

## tags

- [x] tags/search.html results display
  - 表示がいかれてる（生のTextFieldがそのまま表示される）
  - tag 検索なんで タイトルとファイルの中身ちょっとだけでOK
  - 先頭の数行を表示するで良い気がする
  - 簡単に実装できたけど計算量が多すぎてイマイチ

- [x] select multiple dropbox
  - 初のJS `tags.js` を実装 意外とうまくいった

- [x] tags.js
  - `form-tags` の height を Tags.all() ぴったりに出す
  - `select multiple` の height を調整するという意味
  - tags.js 側で調整して終了 `form_tags.size, form_tags.length`

- [x] tags/search.html bug
  - 検索結果 `pre > code` の表示 文字列が長いと見切れる
  - `white-space: pre-wrap` でさくっと改行できた

## problems

- [x] Textarea Markdownize and highlighting
  - `django-markdown` and `highlight.js` 以外の実装を探して確認する
  - なんでかうまく行かなかったので元の方法で実装

- [x] Link に サイト名を表示する
  - `URLField` urllib でドメイン表示する もしくは URLのTitle 取得して表示するなど
  - Model.save() するときに URLField をいい感じに 取得するのが良いのか?
  - Model method としてそのまま実装

- [x] update.html の css
  - create.html では `statement`, `answer` が縦並び
  - update.html では `statement`, `answer` が横並び 修正する

- [x] detail.html のCSS
  - problem.link Headerごちゃごちゃしてるので2行に分けて見やすくする
  - created\_at, update\_at も `<small>` でつけてみる
  - gridlayout にて実装 むしろ見づらくなった気もする
  - そしてcss合わせづらくなる flexbox 二段にして `w-1/3` して Fixedした方がいい

- [x] Textarea height fits its content
  - problems/create, update.html の中身が Textarea の高さに丁度合うように調整
  - 改行の増減に合わせてTextareaの高さを変える
  - `querySelector`, `addEventListener`, `CSSProperties` のいじり方を学ぶ (これは)簡単

- [ ] sort problems list by title, tags, solved count
  - Table の 'th' を押すと昇順降順でソートされる感じ
  - th -> button -> form:get -> if 分岐行けるかも -> `Tags.order_by()`
  - 他のサイト見るともれなく `js` で実装してある それが普通なのか

- [ ] font
  - problems/create and update.html の TextAreaのFont
  - font-family の変え方を知らない 例えば ttf を読み込んで適用 調べる
  - `google-font` はどう見ても簡単そうだけど他の方法も調べとく
  - JetBrains Mono, `Inconsolata`, `FiraCode(Regature)`, `Caskaydia Cove`, HackGen のどれか
  - 何でも良いけど Monospace の方が絶対に書きやすいので（文字の幅が一定のやつ）それらを選択

## searching

- [ ] paginator
  - 検索項目が多かったときに `[first] [1] [2] ... [5] [last]` みたいな表示
  - Django に組み込みの機能があるっぽい -> しかも簡単っぽい

## latex

- [x] Mathjax を利用した数式の美しい表示
  - `script` で MathJax 読み込むだけで終了 なんと簡単な

**Comment by Lootmann** [comment]
# New Features

- [ ] Translations
  - 英文を翻訳する勉強アプリ
  - そのまま組み込む感じ
  - `sentence`, `translate` で Sentenceだけ表示して
  - 翻訳して `translate` を見て確認 Translate は DeepL そのまま持ってくるとかなんとか
  - Model.save() する段階でAPIにつないでお願いする感じ?

**Comment by Lootmann** [comment]
# Ajax

`documents/<int>/translators<int>/update/` で いちいち `update` ボタン押すのはたるいので
`Ctrl+s` でそのまま保存 編集もそのまま続行できる機能

## Asynchronous JavaScript + XML

ボタンを押したら非同期でModelに保存する機能だけ


## TODO

1. udpate.html に JavaScriptを作る

- Ctrl + s を Event で検出する
- もともとのBrowserの挙動 (多分ページのHTMLの保存)を prevent する
- Form の中身を読み取って、document_id, translation_id など必要な情報を送信
- Modelに保存

という操作を裏側で (JavaScript)行う
ユーザー側はボタン押すだけ

**Comment by Lootmann** [comment]
# problems

- [x] Textarea Markdownize and highlighting
  - `django-markdown` and `highlight.js` 以外の実装を探して確認する
  - なんでかうまく行かなかったので元の方法で実装

- [x] Link に サイト名を表示する
  - `URLField` urllib でドメイン表示する もしくは URLのTitle 取得して表示するなど
  - Model.save() するときに URLField をいい感じに 取得するのが良いのか?
  - Model method としてそのまま実装

- [x] update.html の css
  - create.html では `statement`, `answer` が縦並び
  - update.html では `statement`, `answer` が横並び 修正する

- [x] detail.html のCSS
  - problem.link Headerごちゃごちゃしてるので2行に分けて見やすくする
  - created\_at, update\_at も `<small>` でつけてみる
  - gridlayout にて実装 むしろ見づらくなった気もする
  - そしてcss合わせづらくなる flexbox 二段にして `w-1/3` して Fixedした方がいい

- [x] Textarea height fits its content
  - problems/create, update.html の中身が Textarea の高さに丁度合うように調整
  - 改行の増減に合わせてTextareaの高さを変える
  - `querySelector`, `addEventListener`, `CSSProperties` のいじり方を学ぶ (これは)簡単

- [ ] sort problems list by title, tags, solved count
  - Table の 'th' を押すと昇順降順でソートされる感じ
  - th -> button -> form:get -> if 分岐行けるかも -> `Tags.order_by()`
  - 他のサイト見るともれなく `js` で実装してある それが普通なのか

**Comment by Lootmann** [comment]
# Tags

- [x] tags/search.html results display
  - 表示がいかれてる（生のTextFieldがそのまま表示される）
  - tag 検索なんで タイトルとファイルの中身ちょっとだけでOK
  - 先頭の数行を表示するで良い気がする
  - 簡単に実装できたけど計算量が多すぎてイマイチ

- [x] select multiple dropbox
  - 初のJS `tags.js` を実装 意外とうまくいった

- [x] tags.js
  - `form-tags` の height を Tags.all() ぴったりに出す
  - `select multiple` の height を調整するという意味
  - tags.js 側で調整して終了 `form_tags.size, form_tags.length`

- [x] tags/search.html bug
  - 検索結果 `pre > code` の表示 文字列が長いと見切れる
  - `white-space: pre-wrap` でさくっと改行できた


- [x] font
  - problems/create and update.html の TextAreaのFont
  - font-family の変え方を知らない 例えば ttf を読み込んで適用 調べる
  - `google-font` はどう見ても簡単そうだけど他の方法も調べとく
  - JetBrains Mono, `Inconsolata`, `FiraCode(Regature)`, `Caskaydia Cove`, HackGen のどれか
  - 何でも良いけど Monospace の方が絶対に書きやすいので（文字の幅が一定のやつ）それらを選択

**Comment by Lootmann** [comment]
# Searching

- [ ] paginator
  - 検索項目が多かったときに `[first] [1] [2] ... [5] [last]` みたいな表示
  - Django に組み込みの機能があるっぽい -> しかも簡単っぽい
